openshift/prometheus-operator

Dockerfile
cmd/prometheus-config-reloader/Dockerfile

Rebase container images on openshift/origin-base

---

Makefile

@mxinden @squat @s-urbaniak @metalmatze

Change operator target to build only from available files

---

pkg/prometheus/operator.go
pkg/prometheus/rules.go
pkg/prometheus/statefulset.go

cherry-pick of https://github.com/coreos/prometheus-operator/pull/2454
/cc @brancz @mxinden @metalmatze @squat

pkg/prometheus: watch configmaps having the prometheus-name selector

---

Dockerfile.config-reloader.rhel
Dockerfile.rhel

*: fix image builds in brew after moving to golang 1.12

---

Dockerfile.config-reloader
Dockerfile.config-reloader.ocp
Dockerfile.ocp

- Add comments
- rename Dockerfiles
Needs openshift/release#4235 first.
/hold

*: unify Dockerfile naming schema across all monitoring team repos

---

Documentation/api.md
pkg/alertmanager/statefulset.go
pkg/alertmanager/statefulset_test.go
pkg/apis/monitoring/v1/types.go
pkg/prometheus/promcfg_test.go
pkg/prometheus/statefulset.go
pkg/prometheus/statefulset_test.go

@s-urbaniak @LiliC @paulfantom @simonpasquier @pgier @krasi-georgiev

Bug 1762968: Bump Prometheus Operator to latest master

---

pkg/alertmanager/statefulset.go
pkg/alertmanager/statefulset_test.go
pkg/prometheus/statefulset.go
pkg/prometheus/statefulset_test.go

This still needs to be verified on master, but here the cherrypick already.
@s-urbaniak @paulfantom @LiliC @pgier @simonpasquier @krasi-georgiev

Bug 1763098: *: Ensure containers have "FallbackToLogsOnError" termination policy

---

Documentation/rbac.md
Documentation/user-guides/getting-started.md
bundle.yaml
example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
jsonnet/prometheus-operator/prometheus-operator.libsonnet

Backport of: https://github.com/coreos/prometheus-operator/pull/2974

Bug 1805833: Tighten permissions related to CRD create/update

---

OWNERS

/cc @openshift/openshift-team-monitoring

CARRY: OWNERS: add component

---

Documentation/rbac.md
Documentation/user-guides/getting-started.md
bundle.yaml
example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
jsonnet/prometheus-operator/prometheus-operator.libsonnet

Backport of https://github.com/coreos/prometheus-operator/pull/2974

Bug 1805834: Tighten permissions related to CRD create/update

---

cmd/operator/main.go

Backport of https://github.com/coreos/prometheus-operator/pull/3157

Bug 1829501: fix TLS cli parameters

---

pkg/alertmanager/statefulset.go

This is a backport of https://github.com/coreos/prometheus-operator/pull/3271.
/cc @openshift/openshift-team-monitoring

Bug 1813221: pkg/alertmanager: mergepatch alertmanager containers

---

pkg/alertmanager/statefulset.go

This is a backport of https://github.com/coreos/prometheus-operator/pull/3272.
/cc @openshift/openshift-team-monitoring

Bug 1818806: pkg/alertmanager: mergepatch alertmanager containers

---

.github/workflows/e2e.yaml
.gitignore
Makefile
README.md
cmd/admission-webhook/Dockerfile
cmd/admission-webhook/main.go
cmd/operator/main.go
example/admission-webhook/deployment.yaml
example/admission-webhook/service-account.yaml
example/admission-webhook/service-monitor.yaml
example/admission-webhook/service.yaml
jsonnet/prometheus-operator/admission-webhook.libsonnet
pkg/admission/admission.go
pkg/operator/config.go
pkg/server/server.go
pkg/server/server_test.go
scripts/generate/admission-webhook.jsonnet
scripts/generate/build-admission-webhook-example.sh
scripts/push-docker-image.sh
test/framework/framework.go
test/framework/resources/alertmanager-config-validating-webhook.yaml
test/framework/resources/prometheus-operator-mutatingwebhook.yaml
test/framework/resources/prometheus-operator-validatingwebhook.yaml

Cherry pick of https://github.com/prometheus-operator/prometheus-operator/pull/4494
```release-note
```

Standalone webhook server

---

Dockerfile.admission-webhook.ocp
Makefile

Add Dockerfile and targets for standalone admission webhook image

---

Makefile

Fix typo in admission webhook bin output

---

OWNERS

Add JoaoBraveCoding to OWNERS and remove prashbnair and fpetkovski
```release-note
```

Add myself to OWNER file

---

pkg/alertmanager/operator.go
pkg/alertmanager/statefulset.go
pkg/prometheus/operator.go
pkg/prometheus/statefulset.go
pkg/thanos/operator.go
pkg/thanos/statefulset.go

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.
cherry-pick of https://github.com/prometheus-operator/prometheus-operator/pull/4504 to fix https://bugzilla.redhat.com/show_bug.cgi?id=2052201

Bug 2052201: Address race condition in recreate flow for statefulset

---

pkg/apis/monitoring/v1beta1/conversion_from.go
pkg/apis/monitoring/v1beta1/conversion_to.go
vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/conversion_from.go
vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/conversion_to.go

Cherry-pick of https://github.com/prometheus-operator/prometheus-operator/commit/193b342e8a6f2de370e646982dfd756d7a99c898

Bug 2097716: pkg/apis/monitoring/v1beta1: fix httpConfig conversion

---

cmd/prometheus-config-reloader/main.go

Cherry-pick of upstream commit https://github.com/prometheus-operator/prometheus-operator/commit/469ab59d80c5440e0265694b5308cd861554aa07

OCPBUGS-14033: cmd/prometheus-config-reloader: add SIGTERM handler

---

pkg/informers/informers.go
pkg/informers/informers_test.go
vendor/k8s.io/client-go/metadata/fake/simple.go
vendor/modules.txt

cherry-pick of https://github.com/prometheus-operator/prometheus-operator/pull/6298

OCPBUGS-29304: fix: don't fail metadata transform on unknown types (#6298)

---

pkg/informers/informers.go
pkg/informers/informers_test.go
vendor/k8s.io/client-go/metadata/fake/simple.go
vendor/modules.txt

[release-4.15] OCPBUGS-29509: fix: don't fail metadata transform on unknown types (#6298)

---

pkg/alertmanager/amcfg.go
pkg/alertmanager/types.go

Cherry-pick of https://github.com/prometheus-operator/prometheus-operator/pull/6818

OCPBUGS-38174: feat: sync proxy settings in Alertmanager configuration

---

pkg/alertmanager/operator.go
pkg/alertmanager/operator_test.go
pkg/alertmanager/validation/validation.go
pkg/alertmanager/validation/validation_test.go

cherry-picking the change https://github.com/prometheus-operator/prometheus-operator/commit/324ff7cc23823e5270dd2a8cd373f2d40ff08dd7 to 4.18

[release-4.18] OCPBUGS-58194: Fix: One Alertmanager Config failing blocks all others
