openshift/prometheus-operator

- Dockerfile.config-reloader.rhel7
- Dockerfile.rhel7
This change uses multistage builds to generate the container images. It also adds the .rhel7 Dockerfile for OCP builds.
This is similar to https://github.com/openshift/cluster-monitoring-operator/pull/147/.
cc @s-urbaniak @pgier
> Fix Dockerfile files

- pkg/alertmanager/statefulset.go
- pkg/prometheus/statefulset.go
This is step 1 of the strategy outlined in https://bugzilla.redhat.com/show_bug.cgi?id=1700051#c2
```
Unfortunately these are hardcoded into the prometheus-operator as of right now. We're going to go with the following strategy:
* Patch the fork we ship in OpenShift to completely remove the limits.
* Upstream since has added flags to configure these requests/limits, in addition we will add that the 0 value will make the limit/request be removed entirely, and this is what we'll switch to in a future OpenShift version.
```
@mxinden @squat @s-urbaniak @metalmatze @paulfantom
> *: Remove limits

- Dockerfile.config-reloader.rhel
- Dockerfile.rhel
OCP images should be able to be built without contacting external services.
This should fix recent OSBS build problems.
/cc @s-urbaniak
Related to https://github.com/openshift/k8s-prometheus-adapter/pull/17
> *: set -mod="vendor" to build OCP container image

- cmd/operator/main.go
- cmd/operator/main_test.go
- go.mod
- go.sum
- pkg/listwatch/listwatch.go
- pkg/listwatch/namespace_denylist.go
- pkg/listwatch/namespace_denylist_test.go
- pkg/operator/server.go
- pkg/operator/server_test.go
- pkg/prometheus/operator.go
- test/e2e/main_test.go
- test/framework/framework.go
- test/framework/secret.go
- vendor/github.com/brancz/kube-rbac-proxy/LICENSE
- vendor/github.com/brancz/kube-rbac-proxy/pkg/tls/reloader.go
- vendor/k8s.io/component-base/LICENSE
- vendor/k8s.io/component-base/cli/flag/ciphersuites_flag.go
- vendor/k8s.io/component-base/cli/flag/colon_separated_multimap_string_string.go
- vendor/k8s.io/component-base/cli/flag/configuration_map.go
- vendor/k8s.io/component-base/cli/flag/flags.go
- vendor/k8s.io/component-base/cli/flag/langle_separated_map_string_string.go
- vendor/k8s.io/component-base/cli/flag/map_string_bool.go
- vendor/k8s.io/component-base/cli/flag/map_string_string.go
- vendor/k8s.io/component-base/cli/flag/namedcertkey_flag.go
- vendor/k8s.io/component-base/cli/flag/noop.go
- vendor/k8s.io/component-base/cli/flag/omitempty.go
- vendor/k8s.io/component-base/cli/flag/sectioned.go
- vendor/k8s.io/component-base/cli/flag/string_flag.go
- vendor/k8s.io/component-base/cli/flag/tristate.go
- vendor/modules.txt
Backport of https://github.com/coreos/prometheus-operator/pull/3134
Related to https://issues.redhat.com/browse/MON-857
> Add TLS config for prometheus-operator

- Dockerfile.config-reloader.ocp
- Dockerfile.ocp
Bring back multi-arch support. The current implementation in v0.38.1 is incompatible with build system.
/cc @openshift/openshift-team-monitoring @andymcc
> Bug 1834892: CARRY: allow building multi-arch prometheus-operator images downstream

- Dockerfile.config-reloader.ocp
- Dockerfile.ocp
- Fixing maintainer label to end with @redhat.com as this is expected
- Overriding summary label as it is inherited from base image and results with an incorrect value
- explicit golang 1.14 usage
- rearranged Dockerfiles to be similar to other ones used by the team
/cc @openshift/openshift-team-monitoring
> Bug 1867510: fix CVP issues due to incorrect labels set

- pkg/listwatch/listwatch.go
https://github.com/prometheus-operator/prometheus-operator/pull/3340
added a workaround to err out if multiple resource versions are reported from api server.
However the preceeding List function allows multiple resource versions to slip through.
This causes potential cascading failures.
> Bug 1856189: pkg/listwatch: err out with multiple resource versions in List

- Dockerfile.config-reloader.ocp
Updating prometheus-config-reloader builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/prometheus-config-reloader.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating prometheus-config-reloader builder & base images to be consistent with ART

- Dockerfile.ocp
Updating prometheus-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/prometheus-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating prometheus-operator builder & base images to be consistent with ART

- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
Removing liveness probe to prevent killing prometheus pod during WAL
replay.
This should be reverted around kubernetes 1.21 release. At that point
startupProbe should be added.
(cherry picked from commit 35b2954459569674710f7eaf25066658e41c83f6)
**Release Note Template (will be copied)**
```release-note:REPLACEME
```
> Bug 1935586: pkg/prometheus: remove liveness probe

- pkg/alertmanager/operator.go
- pkg/operator/operator.go
- pkg/prometheus/operator.go
- pkg/thanos/operator.go
Cherry-pick the following commits to release-4.8 to fix a bug where waiting for caches synchronization never returns:
- https://github.com/openshift/prometheus-operator/commit/42e8930c6a1610b6c52e10347d15d0ec0a0fc89c - add 10 minute timeout
- https://github.com/openshift/prometheus-operator/commit/80f090bf2827253ad189e8b4a9df026032ac8689 - early exit on error
> Bug 1979575: [4.8]: Add timeout to informers cache sync

- pkg/alertmanager/operator.go
- pkg/alertmanager/operator_test.go
Cherry-pick of https://github.com/prometheus-operator/prometheus-operator/pull/4333 with conflicts addressed 
Background
---
The operator can merge configuration when the
[`AlertmanagerConfigSelector`](https://github.com/prometheus-operator/prometheus-operator/blob/83fe36566f4e0894eb5ffcd2638a0f039a17bdeb/pkg/apis/monitoring/v1/types.go#L1547)
is defined. We are validating (using upstream alertmanager) and
parsing (using internal config) even if we don't need to load config in
memory since the user opted to manage the configuration via the secret.
This can cause problems where there is a missmatch between alertmanager
configuration and the operator internal amcfg struct, for example
prometheus-operator#4174.
Solution
---
Only validate the configuration from upstream `alertmanager` …
> BUG 2041459: alertmanager: only load cfg when writing cfg

- pkg/alertmanager/operator.go
- pkg/alertmanager/statefulset.go
- pkg/prometheus/operator.go
- pkg/prometheus/statefulset.go
- pkg/thanos/operator.go
- pkg/thanos/statefulset.go
cherry-pick of https://github.com/prometheus-operator/prometheus-operator/pull/4504 to fix https://bugzilla.redhat.com/show_bug.cgi?id=20305391
```release-note
```
> Bug 2030539: Address race condition in recreate flow for statefulset

- bundle.yaml
- example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
- example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
- example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
- example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
- jsonnet/prometheus-operator/podmonitors-crd.json
- jsonnet/prometheus-operator/probes-crd.json
- jsonnet/prometheus-operator/prometheuses-crd.json
- jsonnet/prometheus-operator/servicemonitors-crd.json
- pkg/apis/monitoring/v1/types.go
- pkg/prometheus/operator.go
- pkg/prometheus/operator_test.go
- vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
This PR adds cherry-pick of following commits to release-4.10 to add relabel validations which will help to avoid loading wrong configs. This commits were from 0.54.1 release of prometheus-operator and we are doing a downstream patch to 0.53.1 version here which is used in  OpenShift `4.10`
f25ce1b9cb454a2bfd9e48aea3b9927e6668a9a3
1103bd6f41c9378b26c551b428c1902fc3f54710
0d1b38a9eefd05429b238ebf7494de899d60eff5
cc: @simonpasquier
> Bug 2060718: Add relabel validations

- pkg/operator/prober.go
- pkg/operator/prober_test.go
- pkg/prometheus/statefulset.go
- pkg/prometheus/statefulset_test.go
Cherry-pick of https://github.com/prometheus-operator/prometheus-operator/commit/ceac7c9c4b436f37fca2e718153b724ee92be9c9 to avoid simultaneous restarts of Prometheus pods.
By default, the `curl` command returns with a zero exit code (success)
if the endpoint doesn't reply with a 2xx status code. As a result, the
readiness probe would succeed as soon as the Prometheus web server is
ready to respond while `/-/ready` may return "503 Service Not Available"
(e.g. the server hasn't finished loading the TSDB). During a
StatefulSet update with a 2 (or more) replicas, it means that the
StatefulSet controller may recreate the next pod while the last updated
pod hasn't finished its initialization, leading to a service disruption.
The issue is fixed by adding the `--fail` flag to the command. The …
> Bug 2079679: pkg/prometheus: fix curl exec probe

- pkg/operator/config.go
- pkg/thanos/statefulset.go
- pkg/thanos/statefulset_test.go
Issue: https://issues.redhat.com/browse/OCPBUGS-7458
```release-note
```
> OCPBUGS-7458: Fixes ThanoRuler StatefulSet re-creation bug

- Documentation/operator.md
- cmd/admission-webhook/main.go
- cmd/operator/main.go
This change mitigates CVE-2023-44487 by disabling HTTP2 by default and forcing HTTP/1.1 until the Go standard library and golang.org/x/net are fully fixed. Right now, it is possible for authenticated and unauthenticated users to hold open HTTP2 connections and consume huge amounts of memory.
It is possible to revert back the change by using the `--web.enable-http2` argument.
Before this change:
```
curl -kv https://localhost:8443/metrics
*   Trying 127.0.0.1:8443...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN: offers h2,http/1.1
[...]
* ALPN: server accepted h2
[...]
* using HTTP/2
* h2h3 [:method: GET]
* h2h3 [:path: /metrics]
* h2h3 [:scheme: https]
* h2h3 [:authority: localhost:8443]
* h2h3 [user-agent: curl/8.0.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle …
```
> OCPBUGS-21637: fix: disable HTTP2 connections by default

- cmd/admission-webhook/main.go
After disabling HTTP2 connections by default in #6028 started seeing verbose logging in admission webhook pods like:
`ts=2023-11-06T01:50:34.601774794Z caller=stdlib.go:105 caller=server.go:3215 msg="http: superfluous response.WriteHeader call from main.newSrv.func1 (main.go:173)" `
Go doc says If WriteHeader is not called explicitly, the first call to Write will trigger an implicit
WriteHeader(http.StatusOK).
This fix is to change the order of the method invocation so log doesn't complain about this
Signed-off-by: Jayapriya Pai <slashpai9@gmail.com>
(cherry picked from commit 374f4b3d0c58d23318b4f1fd4e0c25b057d34062)
If it fixes a bug or resolves a feature request, be …
> OCPBUGS-22946: fix: remove verbose logging admission-webhook

- Documentation/operator.md
- cmd/admission-webhook/main.go
- cmd/operator/main.go
cherry-picked from upstream prometheus-operator
> [release-4.14] OCPBUGS-20881: fix: disable HTTP2 connections by default

- pkg/apis/monitoring/v1beta1/conversion_from.go
- pkg/apis/monitoring/v1beta1/conversion_to.go
- vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/conversion_from.go
- vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1beta1/conversion_to.go
Cherry-pick of https://github.com/prometheus-operator/prometheus-operator/pull/6282
> OCPBUGS-28251: fix: convert `continue` field between v1beta1 and v1alpha1

- pkg/prometheus/resource_selector.go
- pkg/prometheus/resource_selector_test.go
If a user specify a non-parsable proxyUrl it was not validated/rejected but will break reloading and restarting of Prometheus due to possible invalid syntax.
This commit adds validation and rejects the invalid ones
Manual cherry-pick of prometheus-operator/prometheus-operator#6464
Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.
_Please put a one-line changelog entry below. This will be copied to the changelog file …
> [release-4.15] OCPBUGS-36719: add proxyURL validation for smon,pmon and probe

- pkg/alertmanager/amcfg.go
- pkg/alertmanager/amcfg_test.go
- pkg/alertmanager/testdata/CR_with_EmailConfig_Receiver_Conf.golden
- pkg/alertmanager/testdata/CR_with_EmailConfig_Receiver_Global_Defaults_Conf.golden
- test/e2e/alertmanager_test.go
SMTP smarthost and SMTP from are required
fields which needs to be specified at
either global or at receiver level.
This change will make sure reconciliation fails
if there is empty at both levels.
Related-to #6003
Signed-off-by: Jayapriya Pai <slashpai9@gmail.com>
(cherry picked from commit 58b1d22c294f8a3cb5911f0af92dd576d81d50d6)
> [release-4.18] OCPBUGS-48050: fix: validate smtp smarthost and smtp from fields
